### PR TITLE
Add functionality to search by nama lokasi and wilayah

### PR DESCRIPTION
**Pull request by hendrasan**
This PR adds nama_lokasi_vaksinasi and wilayah to the search dropdown

### CODE REVIEW

**Comment by tibudiyanto** [comment]
Hmm, for me, it made sense to search kecamatan / kelurahan cuz they know theirs. But idk about location.

**Comment by hendrasan** [comment]
Maybe set it back to default to kecamatan search, but allow searching for name and wilayah?

My use case was, I wanted to know any location in Jaksel, disregarding the kecamatan/kelurahan, and I couldn't.

**Comment by pveyes** [comment]
maybe we need better fuzzy search so we can get rid of select input entirely? wdyt? even I sometimes forgot what's kecamatan / kelurahan

**Comment by tibudiyanto** [comment]
fuzzy the entire thing? sounds good to me lol

**Comment by pveyes** [comment]
should be easy using fuse https://fusejs.io/examples.html#search-object-array

**Pull request closed without merging**
