### PR TITLE
Attach last updated detail onto each cards

### LINKED ISSUE #10: Attach last updated infos into each of the location card
image

put it somewhere cute will you ;)

### PR DESCRIPTION
**Pull request by angeloanan**
This PR adds the last updated detail into each cards. 

image
image

Known bug: Tooltip arrow points innacurrately as the boxsize of the text is 100%

Closes #10

### CODE REVIEW

**Comment by tibudiyanto** [comment]
Bahasa indonesia dong :)

**Comment by angeloanan** [comment]
Waduh bahasa indonya apa ya? `Info terakhir diperbaharui 10 menit yang lalu`?

**Comment by angeloanan** [comment]
Looks good?

image

**Comment by angeloanan** [comment]
@tibudiyanto Ready for merge. Merge conflict resolved, rebased from https://github.com/tibudiyanto/jakarta-vax-availability/commit/29f7bb60bfe305cdcec485c6246888082535c1c0

**Comment by juaan** [comment]
how about `Terakhir diperbarui: 01 Jan 1970 12:00` or `Terakhir diperbarui: 01/12/1970 12:00`

**Comment by masbagal** [comment]
Chipping in alternative ideas, feel free to ignore:
- `Diperbarui ...`
- `Data diperoleh ...`

Since using `formatDistanceToNow`, it's kind of readable (?)
- `Diperbarui kurang dari 5 menit yang lalu`
- `Data diperoleh kurang dari 5 menit yang lalu`

**Comment by resir014** [comment]
@angeloanan conflicts, please resolve.

**Comment by angeloanan** [comment]
@resir014 merge conflict resolved, rebased from https://github.com/tibudiyanto/jakarta-vax-availability/commit/399bda7bccae61fa7a147ce83ac7ea37af5f4bc7

**Review by pveyes — APPROVED** [review]
personally would use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat but this is fine as well

cc @tibudiyanto for green CI :D

**Comment by angeloanan** [comment]
I forgot Intl existed. I can refactor in a bit if needed

**Comment by pveyes** [comment]
let's do it in separate PR if you want to, we can merge this first to reduce possible conflict 😁

**Pull request merged**
