### PR TITLE
Improve layout

### LINKED ISSUE #23: Redesign - Basic layout (header, footer, etc.)

### PR DESCRIPTION
**Pull request by ghost**
Continuing from #11, this PR majorly changes the base layout of the app and improve other things, now based from commit db7b5260eb14caaac6e307d74e8f6bc6f5cf0517.

### CODE REVIEW

**Comment by ghost** [comment]
Fixed and tested building locally.

image

**Comment by resir014** [comment]
@nibraswastaken #16 has been merged - please synchronise.

**Comment by tibudiyanto** [comment]
image

**Comment by ghost** [comment]
Okay now I'm certain this works. Sorry about that.

**Comment by tibudiyanto** [comment]
conflictsss

**Comment by ghost** [comment]
Done 🙏🏻

**Comment by resir014** [comment]
Awesome, thanks!

**Pull request merged**
