### PR TITLE
feat: add gmaps route direction

### PR DESCRIPTION
**Pull request by juaan**
## Summary

add `Lihat Rute` button in VaxLocation, I used namaLokasi instead of lat and lon, because when I used lat and lon, the place is different in gmaps

## Preview Video

https://user-images.githubusercontent.com/20969634/124467236-c9dc0b80-ddc1-11eb-9fb2-165e233ad4e5.mov

### CODE REVIEW

**Comment by pveyes** [comment]
this is duplicate from #7 right? cc @angeloanan does lat/lon works in your PR? Personally I prefer to use lat/lon as it's more consistent than search keyword

also this might affect #25

**Comment by angeloanan** [comment]
PR #7 uses lat/lon on Google Maps search which will direct user to a dropped pin on the said location. If the API doesn't provide any lat/lon, the link will resolve to a search for the vaccination site's name instead.

**Comment by tibudiyanto** [comment]
i too prefer lat lon then search

**Comment by juaan** [comment]
Ah I see, I think we can use https://github.com/tibudiyanto/jakarta-vax-availability/pull/7, and we can close this PR, thank you guys!

**Comment by resir014** [comment]
Superseded by #7.

**Pull request closed without merging**
