### PR TITLE
Init PWA manifest

### PR DESCRIPTION
**Pull request by antonybudianto**
Init PWA manifest so it can be installed on supported browser

On Chrome:
Screen Shot 2021-07-06 at 07 57 54
Screen Shot 2021-07-06 at 07 58 03

iOS homescreen icon
210279543_2704141143216386_7326770887867841340_n (2)

iOS PWA
210663336_828997544712740_1694001750773648679_n (1)

Android:
Need android users volunteers 🙏

Favicon generated using https://favicon.io/

### CODE REVIEW

**Comment by resir014** [comment]
I think we should hold off on merging this until we completed our code maintainability (#26) and redesign (#21) epics. We still have some things in store atm.

**Comment by resir014** [comment]
Also, can we use the current icon that we have first instead of a new one? @antonybudianto

**Comment by antonybudianto** [comment]
Hi @resir014 , yes we can use https://favicon.io/emoji-favicons/face-with-medical-mask

**Review by resir014 — APPROVED** [review]

**Comment by tibudiyanto** [comment]
should i merge this? @resir014 @pveyes

**Comment by pveyes** [comment]
lets go

**Pull request merged**
