### PR TITLE
Add Google Maps search link

### PR DESCRIPTION
**Pull request by angeloanan**
This PR adds google maps search when clicking on the vaccination site.

### CODE REVIEW

**Comment by angeloanan** [comment]
Just realized, if the API is accurate, then we can use the lat / lon data from it.

Refactoring...

**Comment by angeloanan** [comment]
Rebased with #9. Might be in conflict again with #11.

**Comment by angeloanan** [comment]
@tibudiyanto Ready for merge. Rebased from https://github.com/tibudiyanto/jakarta-vax-availability/commit/29f7bb60bfe305cdcec485c6246888082535c1c0

**Review by pveyes — APPROVED** [review]
LGTM let's do UI adjustment later

**Comment by pveyes** [comment]
cc @tibudiyanto might need vercel auth for last check

**Comment by pveyes** [comment]
whoops another conflict 🙏

**Comment by angeloanan** [comment]
@pveyes @tibudiyanto resolved conflict. 

image

**Pull request merged**
