### PR TITLE
wip: virtualized vax list

### LINKED ISSUE #67: Implement pagination/virtualised list to improve page load time.
## Description

With the recent update to the vax API, the site's now loading slowly due to the number of data. We should implement some form of pagination to help reduce the number of content rendered.

## Implementation Model

A basic pagination query of the API is now available on the API. https://jkt-vax-quota.vercel.app/

Available queries: start (default 1) and count (default 100).

e.g. `https://jkt-vax-quota.vercel.app/api/kuota?start=10&count=100`

## Tasks

[TODO]

### LINKED ISSUE #70: Reduce bundle size
## Description

Huge bundle size, and very high TBT
image

image

## Expected Behaviour

800kB is definitely excessive. We should aim at most 200kB based on recommendation alone. Less would be better

### PR DESCRIPTION
**Pull request by pveyes**
resolve #67 

Implement virtualized list using `VariableSizeGrid` with 2 column. This is currently hardcoded as we probably need some kind of media query to switch to single column grid (still not sure the best way to handle this)

**Some notes**
- Grid height is calculated based on number of schedule available in the vax location
- We use the `filteredSchedule` itself as key to make sure that the virtual list re-renders on query change

## To do
- [ ] make it responsive
- [ ] put footer back / remove entirely 

## Trade Off

- Footer must be fixed / removed entirely
- Scroll not on body

## Before
image

## After
image

also resolve #70

### CODE REVIEW

**Comment by sonnylazuardi** [comment]
Is it possible to keep the scroll on body?

**Comment by sonnylazuardi** [comment]
image

need to handle virtual list on mobile

**Comment by sonnylazuardi** [comment]
https://codesandbox.io/s/rcv-rwd-x6lvc?fontsize=14&hidenavigation=1&theme=dark this might be helpful for responsive layout

**Comment by resir014** [comment]
We might be able to use something like [Simplebar](https://grsmto.github.io/simplebar/) to create a custom scrollbar that looks better than the default one, if we can't move it out of the center of the body.

Otherwise, we might have to improve our application shell UI.

**Comment by pveyes** [comment]
decided to ship client-side pagination instead. The trade off of using virtualized list is not favorable

**Pull request closed without merging**
