### PR TITLE
Add empty quota indicator

### PR DESCRIPTION
**Pull request by masbagal**
Add indicator for location with no quota to reduce clicking schedule only to found no quota

Screen Shot 2021-07-05 at 20 00 05

### CODE REVIEW

**Comment by resir014** [comment]
@masbagal Conflicts, please resolve.

**Comment by masbagal** [comment]
Resolved @resir014 🙇🏻

**Comment by pveyes** [comment]
Sweet

**Comment by pveyes** [comment]
Just realized we probably need to have some kind of feature parity checklist between home & map page

If it's implemented in one page there's a high chance we'll need the equivalent in the other page as well

**Comment by sonnylazuardi** [comment]
> Just realized we probably need to have some kind of feature parity checklist between home & map page
> 
> If it's implemented in one page there's a high chance we'll need the equivalent in the other page as well

I reused VaxLocation component in map page
https://github.com/tibudiyanto/jakarta-vax-availability/pull/30

**Review by pveyes — APPROVED** [review]
let's ship this first and reiterate better visual as described in #25 later

**Pull request merged**
